version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: kumdori-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      TZ: "${TZ}"

    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --default-time-zone=${TZ}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: ghcr.io/lyj0304/kumdorigrow:latest
    container_name: kumdori-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=mysql # DB_HOST를 'mysql'로 설정하여 Docker 내부 통신을 보장
      - OCR_ENABLED=${OCR_ENABLED}
      - OCR_API_URL=${CLOVA_OCR_URL}
      - OCR_API_KEY=${CLOVA_OCR_SECRET}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: