version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: kumdori-mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      TZ: "${TZ}"
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --default-time-zone=${TZ}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: ghcr.io/iyj0304/kumdorigrow:latest
    container_name: kumdori-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: