spring:
  datasource:
    url: jdbc:mysql://localhost:3308/kumdori_grow?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: app_user
    password: heathunting
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update   # ← 엔티티 기반으로 테이블 자동 생성
    open-in-view: false
flyway:
  enabled: false         # ← 사용 안 함

ocr:
  clova:
    url: ${CLOVA_OCR_URL}
    secret: ${CLOVA_OCR_SECRET}

kumdori:
  xp:
    weights:
      FRANCHISE: 0.6
      LOCAL: 1.0
      MARKET: 2.0

server:
  port: 8082