# 공통(default)
server:
  port: ${SERVER_PORT}   # 컨테이너 내부 포트는 8080 권장

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

# (선택) 헬스체크용 액추에이터를 쓰면 노출
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true

flyway:
  enabled: false

ocr:
  clova:
    url: ${CLOVA_OCR_URL}
    secret: ${CLOVA_OCR_SECRET}

kumdori:
  xp:
    weights:
      FRANCHISE: 0.6
      LOCAL: 1.0
      MARKET: 2.0

---
spring:
  config:
    activate:
      on-profile: local
# 로컬도 환경변수에서만 읽어오게 유지 (하드코딩 금지)
server:
  port: ${SERVER_PORT}

# ========= prod profile (env-only) =========
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: ${SERVER_PORT}